project_id = "djskqegnpplmnyrzomri"

[functions.ai-sql-orchestrator]
verify_jwt = true

[functions.manage-schema-table]
verify_jwt = true

[functions.insert-clean-data]
verify_jwt = true

[functions.migrate-business-context]
verify_jwt = true

[functions.generate-session-title]
verify_jwt = true

[functions.ai-chart-generator]
verify_jwt = true
[functions.ai-sql-gen]
enabled = true
verify_jwt = true
import_map = "./functions/ai-sql-gen/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-sql-gen/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-sql-gen/*.html" ]
